# Generated by Django 4.2.25 on 2026-05-04 09:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import myapp.api.models.events
import myapp.api.models.users
import uuid


# Functions from the following migrations need manual copying.
# Move them and any dependencies into this file, then update the
# RunPython operations to refer to the local versions:
# myapp.api.migrations.0002_customuser_preferred_name
def populate_preferred_name(apps, schema_editor):
    CustomUser = apps.get_model('api', 'CustomUser')
    Inductee = apps.get_model('api', 'Inductee')
    Member = apps.get_model('api', 'Member')
    for user in CustomUser.objects.all():
        inductee = Inductee.objects.filter(user=user.user_id).first()
        member = Member.objects.filter(user=user.user_id).first()
        if user.groups.filter(name='inductee').exists() and inductee:
            user.preferred_name = inductee.preferred_name
        if user.groups.filter(name='member').exists() and member:
            user.preferred_name = member.preferred_name
        user.save()
    
class Migration(migrations.Migration):

    replaces = [('api', '0001_initial'), ('api', '0002_customuser_preferred_name'), ('api', '0003_remove_inductee_preferred_name_and_more'), ('api', '0004_alter_event_hosts'), ('api', '0005_inductionclass_event_event_photo_and_more'), ('api', '0006_event_is_time_restricted_and_more'), ('api', '0007_remove_event_event_photo_event_embed_code'), ('api', '0008_alter_inductee_grad_year_alter_member_grad_year'), ('api', '0009_alter_customuser_induction_class'), ('api', '0010_event_rides'), ('api', '0011_degreelevel_major'), ('api', '0012_quarter_outreachstudent_quarter'), ('api', '0013_inductionclass_availabilities'), ('api', '0014_alter_inductee_grad_year_alter_member_grad_year'), ('api', '0015_house_customuser_bio_customuser_degree_and_more'), ('api', '0016_alter_customuser_profile_picture'), ('api', '0017_customuser_current_courses_member_current_courses'), ('api', '0015_customuser_bio_customuser_degree_and_more'), ('api', '0016_remove_customuser_bio_remove_customuser_degree_and_more'), ('api', '0018_resolve_conflicts'), ('api', '0019_customuser_bio_customuser_degree_and_more'), ('api', '0020_alter_customuser_grad_year_alter_inductee_grad_year_and_more'), ('api', '0021_synclock')]

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('user_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('middle_name', models.CharField(blank=True, max_length=65, null=True)),
                ('pronouns', models.CharField(blank=True, max_length=65, null=True)),
                ('email', models.EmailField(max_length=65, unique=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', myapp.api.models.users.CustomUserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('time_last_modified', models.DateTimeField(auto_now=True)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('points', models.FloatField(default=1)),
                ('description', models.TextField(blank=True)),
                ('is_draft', models.BooleanField(default=True)),
                ('start_time', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('end_time', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('anon_viewable', models.BooleanField(default=False)),
            ],
            options={
                'permissions': [('can_view_draft', 'Can view drafts of events'), ('can_view_relevant_users', 'Can view all users involved with an event, not just oneself')],
            },
        ),
        migrations.CreateModel(
            name='EventType',
            fields=[
                ('name', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='OutreachStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car', models.CharField(default='No', max_length=65)),
                ('outreach_course', models.CharField(default='None', max_length=65)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Officer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(blank=True, max_length=65, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferred_name', models.CharField(blank=True, max_length=65, null=True)),
                ('major', models.CharField(max_length=65, null=True)),
                ('degree', models.CharField(default='Undergraduate', max_length=65)),
                ('grad_year', models.IntegerField(default=2023)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Inductee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferred_name', models.CharField(blank=True, max_length=65, null=True)),
                ('major', models.CharField(blank=True, max_length=65, null=True)),
                ('degree', models.CharField(default='Undergraduate', max_length=65)),
                ('grad_year', models.IntegerField(default=2023)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EventActionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField(auto_now_add=True)),
                ('action', models.TextField(blank=True, choices=[('RSVP', 'RSVP'), ('Sign In', 'Sign In'), ('Check Off', 'Check Off')], null=True)),
                ('details', models.TextField(blank=True)),
                ('points', models.FloatField(default=0)),
                ('extra_data', models.JSONField(default=myapp.api.models.events.EventActionRecord.default_extra_data)),
                ('acted_on', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='actions_received', to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions_taken', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='event_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.eventtype'),
        ),
        migrations.AddField(
            model_name='event',
            name='hosts',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='event',
            name='view_groups',
            field=models.ManyToManyField(blank=True, related_name='viewable_events', to='auth.group'),
        ),
        migrations.AddConstraint(
            model_name='eventactionrecord',
            constraint=models.UniqueConstraint(fields=('acted_on', 'event', 'action'), name='unique_action_per_user_event_pair'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='preferred_name',
            field=models.CharField(default='', max_length=65),
            preserve_default=False,
        ),
        migrations.RunPython(
            code=populate_preferred_name,
        ),
        migrations.RemoveField(
            model_name='inductee',
            name='preferred_name',
        ),
        migrations.RemoveField(
            model_name='member',
            name='preferred_name',
        ),
        migrations.AlterField(
            model_name='event',
            name='hosts',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='InductionClass',
            fields=[
                ('name', models.CharField(max_length=65, primary_key=True, serialize=False, unique=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('academic_year', models.IntegerField()),
                ('rollover_event', models.CharField(blank=True, max_length=65, null=True, unique=True)),
                ('form_active', models.BooleanField(default=False)),
                ('rollover_points', models.JSONField(default=dict)),
                ('availabilities', models.JSONField(default=dict)),
            ],
        ),
        migrations.AddField(
            model_name='inductee',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='event',
            name='is_time_restricted',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='event',
            name='embed_code',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='inductee',
            name='grad_year',
            field=models.IntegerField(default=2024),
        ),
        migrations.AlterField(
            model_name='member',
            name='grad_year',
            field=models.IntegerField(default=2024),
        ),
        migrations.AddField(
            model_name='customuser',
            name='induction_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.inductionclass'),
        ),
        migrations.AddField(
            model_name='event',
            name='rides',
            field=models.JSONField(default=dict),
        ),
        migrations.CreateModel(
            name='DegreeLevel',
            fields=[
                ('name', models.CharField(max_length=65, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Major',
            fields=[
                ('name', models.CharField(max_length=65, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Quarter',
            fields=[
                ('name', models.CharField(max_length=65, primary_key=True, serialize=False, unique=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('academic_year', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='outreachstudent',
            name='quarter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.quarter'),
        ),
        migrations.AlterField(
            model_name='inductee',
            name='grad_year',
            field=models.IntegerField(default=2025),
        ),
        migrations.AlterField(
            model_name='member',
            name='grad_year',
            field=models.IntegerField(default=2025),
        ),
        migrations.CreateModel(
            name='House',
            fields=[
                ('name', models.CharField(max_length=65, primary_key=True, serialize=False, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('color', models.CharField(default='Blue', max_length=20)),
                ('logo', models.CharField(default='/static/HouseLogo.png', max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='customuser',
            name='bio',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='degree',
            field=models.CharField(default='Undergraduate', max_length=65),
        ),
        migrations.AddField(
            model_name='customuser',
            name='grad_year',
            field=models.IntegerField(default=2025),
        ),
        migrations.AddField(
            model_name='customuser',
            name='major',
            field=models.CharField(blank=True, max_length=65, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='profile_picture',
            field=models.CharField(default='/static/profile_icons/User.png', max_length=200),
        ),
        migrations.AddField(
            model_name='customuser',
            name='social_links',
            field=models.JSONField(default={'github': {'icon': 'GitHub', 'link': 'https://www.github.com/', 'username': ''}, 'instagram': {'icon': 'Instagram', 'link': 'https://www.instagram.com/', 'username': ''}, 'linkedin': {'icon': 'LinkedIn', 'link': 'https://www.linkedin.com/in/', 'username': ''}}),
        ),
        migrations.AlterField(
            model_name='member',
            name='major',
            field=models.CharField(blank=True, max_length=65, null=True),
        ),
        migrations.CreateModel(
            name='HousePointRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.FloatField(default=0)),
                ('description', models.TextField(blank=True, null=True)),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('added_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='house_points_added', to=settings.AUTH_USER_MODEL)),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='point_records', to='api.house')),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='house_points_earned', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HouseMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_house_leader', models.BooleanField(default=False)),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='api.house')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'house')},
            },
        ),
        migrations.AddField(
            model_name='customuser',
            name='current_courses',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='member',
            name='current_courses',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='member',
            name='major',
            field=models.CharField(blank=True, max_length=65, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='major',
            field=models.CharField(max_length=65, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='grad_year',
            field=models.IntegerField(default=2026),
        ),
        migrations.AlterField(
            model_name='inductee',
            name='grad_year',
            field=models.IntegerField(default=2026),
        ),
        migrations.AlterField(
            model_name='member',
            name='grad_year',
            field=models.IntegerField(default=2026),
        ),
        migrations.CreateModel(
            name='SyncLock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_syncing', models.BooleanField(default=False)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Sync Lock',
                'verbose_name_plural': 'Sync Locks',
            },
        ),
    ]
