# Generated by Django 4.2.3 on 2023-09-08 04:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="inductee",
            old_name="foreign_key",
            new_name="user_id",
        ),
        migrations.RenameField(
            model_name="member",
            old_name="foreign_key",
            new_name="user_id",
        ),
    ]
