# Generated by Django 4.2.3 on 2023-09-08 04:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_rename_foreign_key_inductee_user_id_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="inductee",
            old_name="user_id",
            new_name="user",
        ),
        migrations.RenameField(
            model_name="member",
            old_name="user_id",
            new_name="user",
        ),
    ]
