# Generated by Django 4.2.3 on 2023-10-15 00:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_customuser_preferred_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="inductee",
            name="preferred_name",
        ),
        migrations.RemoveField(
            model_name="member",
            name="preferred_name",
        ),
    ]
