# Generated by Django 4.2.3 on 2023-09-03 02:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_customuser_preferred_name_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="username",
        ),
        migrations.AlterField(
            model_name="customuser",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
