# Generated by Django 4.2.3 on 2023-09-01 23:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("api", "0003_alter_eventtype_view_groups"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="attendees",
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name="eventtype",
            name="edit_groups",
            field=models.ManyToManyField(
                blank=True, related_name="editable_event_types", to="auth.group"
            ),
        ),
        migrations.AlterField(
            model_name="eventtype",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
