# Generated by Django 4.2.3 on 2023-11-17 18:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0006_event_is_time_restricted_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="event",
            name="event_photo",
        ),
        migrations.AddField(
            model_name="event",
            name="embed_code",
            field=models.TextField(blank=True),
        ),
    ]
