# Generated by Django 4.2.3 on 2024-01-11 04:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0007_remove_event_event_photo_event_embed_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inductee",
            name="grad_year",
            field=models.IntegerField(default=2024),
        ),
        migrations.AlterField(
            model_name="member",
            name="grad_year",
            field=models.IntegerField(default=2024),
        ),
    ]
