# Generated by Django 4.2.3 on 2024-01-18 07:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0008_alter_inductee_grad_year_alter_member_grad_year"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="induction_class",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="api.inductionclass",
            ),
        ),
    ]
