# Generated by Django 4.2.3 on 2024-02-01 20:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0009_alter_customuser_induction_class"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="rides",
            field=models.JSONField(default=dict),
        ),
    ]
