# Generated by Django 4.2.3 on 2024-02-16 17:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0010_event_rides"),
    ]

    operations = [
        migrations.CreateModel(
            name="DegreeLevel",
            fields=[
                (
                    "name",
                    models.CharField(
                        max_length=65, primary_key=True, serialize=False, unique=True
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Major",
            fields=[
                (
                    "name",
                    models.CharField(
                        max_length=65, primary_key=True, serialize=False, unique=True
                    ),
                ),
            ],
        ),
    ]
