# Generated by Django 4.2.3 on 2024-02-20 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0011_degreelevel_major"),
    ]

    operations = [
        migrations.CreateModel(
            name="Quarter",
            fields=[
                (
                    "name",
                    models.CharField(
                        max_length=65, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("academic_year", models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name="outreachstudent",
            name="quarter",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="api.quarter",
            ),
        ),
    ]
