# Generated by Django 4.2.3 on 2024-12-04 17:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0012_quarter_outreachstudent_quarter"),
    ]

    operations = [
        migrations.AddField(
            model_name="inductionclass",
            name="availabilities",
            field=models.JSONField(default=dict),
        ),
    ]
