# Generated by Django 4.2.3 on 2025-01-07 02:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0013_inductionclass_availabilities"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inductee",
            name="grad_year",
            field=models.IntegerField(default=2025),
        ),
        migrations.AlterField(
            model_name="member",
            name="grad_year",
            field=models.IntegerField(default=2025),
        ),
    ]
