# Generated by Django 4.2.3 on 2025-04-02 01:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0014_alter_inductee_grad_year_alter_member_grad_year"),
    ]

    operations = [
        migrations.CreateModel(
            name="House",
            fields=[
                (
                    "name",
                    models.CharField(
                        max_length=65, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("color", models.CharField(default="Blue", max_length=20)),
                (
                    "logo",
                    models.CharField(default="/static/HouseLogo.png", max_length=200),
                ),
            ],
        ),
        migrations.AddField(
            model_name="customuser",
            name="bio",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="degree",
            field=models.CharField(default="Undergraduate", max_length=65),
        ),
        migrations.AddField(
            model_name="customuser",
            name="grad_year",
            field=models.IntegerField(default=2025),
        ),
        migrations.AddField(
            model_name="customuser",
            name="major",
            field=models.CharField(blank=True, max_length=65, null=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="profile_picture",
            field=models.CharField(
                default="/static/profile_icons/UserProfile.png", max_length=200
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="social_links",
            field=models.JSONField(
                default={
                    "github": {
                        "icon": "GitHub",
                        "link": "https://www.github.com/",
                        "username": "",
                    },
                    "instagram": {
                        "icon": "Instagram",
                        "link": "https://www.instagram.com/",
                        "username": "",
                    },
                    "linkedin": {
                        "icon": "LinkedIn",
                        "link": "https://www.linkedin.com/in/",
                        "username": "",
                    },
                }
            ),
        ),
        migrations.AlterField(
            model_name="member",
            name="major",
            field=models.CharField(blank=True, max_length=65, null=True),
        ),
        migrations.CreateModel(
            name="HousePointRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("points", models.FloatField(default=0)),
                ("description", models.TextField(blank=True, null=True)),
                ("date_added", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "added_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="house_points_added",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "house",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="point_records",
                        to="api.house",
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="house_points_earned",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="HouseMembership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("is_house_leader", models.BooleanField(default=False)),
                (
                    "house",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="members",
                        to="api.house",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "house")},
            },
        ),
    ]
