# Generated by Django 4.2.3 on 2025-02-19 21:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0014_alter_inductee_grad_year_alter_member_grad_year"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="bio",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="degree",
            field=models.CharField(default="Undergraduate", max_length=65),
        ),
        migrations.AddField(
            model_name="customuser",
            name="grad_year",
            field=models.IntegerField(default=2025),
        ),
        migrations.AddField(
            model_name="customuser",
            name="major",
            field=models.CharField(blank=True, max_length=65, null=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="social_links",
            field=models.JSONField(
                default={
                    "github": {
                        "icon": "GitHub",
                        "link": "https://www.github.com/",
                        "username": "",
                    },
                    "instagram": {
                        "icon": "Instagram",
                        "link": "https://www.instagram.com/",
                        "username": "",
                    },
                    "linkedin": {
                        "icon": "LinkedIn",
                        "link": "https://www.linkedin.com/in/",
                        "username": "",
                    },
                }
            ),
        ),
        migrations.AlterField(
            model_name="member",
            name="major",
            field=models.CharField(blank=True, max_length=65, null=True),
        ),
    ]
