# Generated by Django 4.2.3 on 2025-02-19 22:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0015_customuser_bio_customuser_degree_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="bio",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="degree",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="grad_year",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="major",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="social_links",
        ),
        migrations.AlterField(
            model_name="member",
            name="major",
            field=models.CharField(max_length=65, null=True),
        ),
    ]
