# Generated by Django 4.2.3 on 2025-04-02 02:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0015_house_customuser_bio_customuser_degree_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="profile_picture",
            field=models.CharField(
                default="/static/profile_icons/User.png", max_length=200
            ),
        ),
    ]
