# Generated by Django 4.2.3 on 2025-04-13 01:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0016_alter_customuser_profile_picture"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="current_courses",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="member",
            name="current_courses",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
