# Generated by Django 4.2.3 on 2025-10-08 22:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0016_remove_customuser_bio_remove_customuser_degree_and_more"),
        ("api", "0017_customuser_current_courses_member_current_courses"),
    ]

    operations = []
