# Generated by Django 4.2.25 on 2026-01-14 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_customuser_bio_customuser_degree_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='grad_year',
            field=models.IntegerField(default=2026),
        ),
        migrations.AlterField(
            model_name='inductee',
            name='grad_year',
            field=models.IntegerField(default=2026),
        ),
        migrations.AlterField(
            model_name='member',
            name='grad_year',
            field=models.IntegerField(default=2026),
        ),
    ]
