# Generated by Django 4.2.27 on 2026-04-29 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_customuser_bio_customuser_degree_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SyncLock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_syncing', models.BooleanField(default=False)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Sync Lock',
                'verbose_name_plural': 'Sync Locks',
            },
        ),
        migrations.AlterField(
            model_name='customuser',
            name='grad_year',
            field=models.IntegerField(default=2026),
        ),
        migrations.AlterField(
            model_name='inductee',
            name='grad_year',
            field=models.IntegerField(default=2026),
        ),
        migrations.AlterField(
            model_name='member',
            name='grad_year',
            field=models.IntegerField(default=2026),
        ),
    ]
