# Generated by Django 4.2.3 on 2023-10-15 00:27

from django.db import migrations, models

def populate_preferred_name(apps, schema_editor):
    CustomUser = apps.get_model('api', 'CustomUser')
    Inductee = apps.get_model('api', 'Inductee')
    Member = apps.get_model('api', 'Member')
    for user in CustomUser.objects.all():
        inductee = Inductee.objects.filter(user=user.user_id).first()
        member = Member.objects.filter(user=user.user_id).first()
        if user.groups.filter(name='inductee').exists() and inductee:
            user.preferred_name = inductee.preferred_name
        if user.groups.filter(name='member').exists() and member:
            user.preferred_name = member.preferred_name
        user.save()

class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="preferred_name",
            field=models.CharField(default="", max_length=65),
            preserve_default=False,
        ),
        migrations.RunPython(populate_preferred_name),
    ]
