# Generated by Django 4.2.3 on 2023-11-03 05:31

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0004_alter_event_hosts"),
    ]

    operations = [
        migrations.CreateModel(
            name="InductionClass",
            fields=[
                (
                    "name",
                    models.CharField(
                        max_length=65, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("academic_year", models.IntegerField()),
                (
                    "rollover_event",
                    models.CharField(blank=True, max_length=65, null=True, unique=True),
                ),
                ("form_active", models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name="event",
            name="event_photo",
            field=models.ImageField(blank=True, null=True, upload_to="images/"),
        ),
        migrations.AddField(
            model_name="inductee",
            name="date_created",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="customuser",
            name="induction_class",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="api.inductionclass",
            ),
        ),
    ]
