# Generated by Django 4.2.3 on 2023-11-08 01:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0005_inductionclass_event_event_photo_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="is_time_restricted",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="inductionclass",
            name="rollover_points",
            field=models.JSONField(default=dict),
        ),
    ]
